//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiKairos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class celulares
    {
        public celulares()
        {
            this.coberturas_celular = new HashSet<coberturas_celular>();
        }
    
        public int id_celular { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<coberturas_celular> coberturas_celular { get; set; }
    }
}
