//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiKairos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indumentarias
    {
        public int id_indumentaria { get; set; }
        public string nombre { get; set; }
        public Nullable<int> valor_riesgo { get; set; }
        public byte[] cdate { get; set; }
        public Nullable<byte> estado { get; set; }
    }
}
