//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiKairos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfiles_riesgos
    {
        public int id_perfil { get; set; }
        public Nullable<int> id_sector { get; set; }
        public string calzada { get; set; }
        public string senalizacion { get; set; }
        public string tipo_iluminacion { get; set; }
        public string flujo_vehicular { get; set; }
        public Nullable<int> control_policia { get; set; }
    
        public virtual sectores sectores { get; set; }
    }
}
