//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiKairos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectores
    {
        public sectores()
        {
            this.coberturas_celular = new HashSet<coberturas_celular>();
            this.perfiles_riesgos = new HashSet<perfiles_riesgos>();
            this.rutas = new HashSet<rutas>();
            this.telefonos_emergencias = new HashSet<telefonos_emergencias>();
            this.velocidades = new HashSet<velocidades>();
        }
    
        public int id_sector { get; set; }
        public string punto_inicio { get; set; }
        public string punto_fin { get; set; }
        public string distancia { get; set; }
        public Nullable<int> accidentabilidad { get; set; }
    
        public virtual ICollection<coberturas_celular> coberturas_celular { get; set; }
        public virtual ICollection<perfiles_riesgos> perfiles_riesgos { get; set; }
        public virtual ICollection<rutas> rutas { get; set; }
        public virtual ICollection<telefonos_emergencias> telefonos_emergencias { get; set; }
        public virtual ICollection<velocidades> velocidades { get; set; }
    }
}
