//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiKairos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class velocidades
    {
        public int id_velocidad { get; set; }
        public Nullable<int> id_sector { get; set; }
        public string detalle { get; set; }
    
        public virtual sectores sectores { get; set; }
    }
}
